# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2cb20eb79490e7a55e2d2cdee72f3b4ad32ca5e0cb8a3c4305f5759a86d8df30104b8e62cebe16568f39724b4738a45f0270f100323b87e9061c6ba02aff6b68

test:
  secret_key_base: dcca458b5578856c0532e33871eaef58d50cd30fa1d46c96ad49e515c4cc6ea7d72e8146b2682142c3f28a86f26c2c3492426f482c24ae6999dd9e75babbb3a4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
